baseurl = "https://valeriogalano.it/"
title = "Valerio Galano, programmatore e analista software"
theme = "hugo-theme-nix"
languageCode = "it-it"
disqusShortname = ""
pygmentsUseClasses=true

[menu]
#  [[menu.header]]
#    name = "blog"
#    weight = 1
#    url = "/posts"
#  [[menu.header]]
#    name = "about"
#    weight = 1
#    url = "/about"
#  [[menu.header]]
#    parent = "blog"
#    name = "posts"
#    weight = 1
#    url = "/daredevel"
#  [[menu.header]]
#    parent = "blog"
#    name = "categories"
#    weight = 2
#    url = "/categories"
#  [[menu.header]]
#    parent = "blog"
#    name = "tags"
#    weight = 3
#    url = "/tags"

[params]
  GithubID = "daredevel"
  TwitterID = "valeriogalano"
  LinkedInID = "valeriogalano"
#  FacebookID = "valerio.galano"
  TelegramID = "valeriogalano"
  InstagramID = "valeriogalano"
  Name = "Valerio Galano"
  HeaderUsername = "valerio"
  HeaderHostname = "daredevel"
  Email = "v.galano@daredevel.com"
  About = "Prometto che al più presto mi fermerò un attimo e mi prenderò qualche minuto per pensare ad una descrizione da mettere in questo box. Nel frattempo, in alto trovi i collegamenti al mio blog e al mio podcast. Buon divertimento!"
  ProfilePicture = "/img/profile.jpg"
  Favicon = "/img/logo-512x512.png"
  Mobile = "+393803529774"
  description = "Sviluppo software, back-end, api, chatbot, Alexa skills"
  images = ["/img/logo-200x200.png"]
  title = "Valerio Galano"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.vimeo]
    disable = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true