baseurl = "https://valeriogalano.it/"
title = "Valerio Galano, sviluppo software e Web"
theme = "hugo-theme-massively"
languageCode = "it-it"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[params]
  Favicon = "/img/logo-512x512.png"

# Below parameters can be set to override default post settings
[params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
    disableInlineCSS = true
  [privacy.vimeo]
    disable = true
    simple = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true