name: Deploy

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:
  
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.64.0'

    - name: Build
      run: hugo -D

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.daredevel.com/
        ftp-username: ftp_website@valeriogalano.it
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public/
